language: node.js
node_js:
  - 14

sudo: required

services:
  - docker

before_install:
  - echo "REACT_APP_API_BASE_URL=$API_BASE_URL" > .env.production
  - echo "REACT_APP_FILE_URL=$FILE_URL" >> .env.production
  - echo "REACT_APP_MAX_FILE_SIZE=$MAX_FILE_SIZE" >> .env.production

install:
  - yarn install

script:
  - yarn build

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - if [ "${TRAVIS_BRANCH}" == "pre-release" ]; then
    docker build -t poolchm/haribo:pre-release .;
    docker push poolchm/haribo:pre-release;
    elif [ -n "${TRAVIS_TAG}"  ]; then
    docker build -t poolchm/haribo:${TRAVIS_TAG} .;
    docker push poolchm/haribo:${TRAVIS_TAG};
    else
    docker build -t poolchm/haribo:latest .;
    docker push poolchm/haribo:latest;
    fi
