language: node.js
node_js:
  - 14

sudo: required

services:
  - docker

install:
  - yarn install

script:
  - yarn build

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t poolchm/haribo:latest .
  - docker push poolchm/haribo:latest
  - if [ -n "${TRAVIS_TAG}"  ]; then
    docker build -t poolchm/haribo:${TRAVIS_TAG} .;
    docker push poolchm/haribo:${TRAVIS_TAG};
    fi
