language: node.js
node_js:
  - 14

sudo: required

services:
  - docker

before_install:
  - echo "REACT_APP_API_BASE_URL=$REACT_APP_TEST_API_BASE_URL" > .env
  - echo "REACT_APP_FILE_URL=$REACT_APP_TEST_FILE_URL" >> .env
  - echo "REACT_APP_MAX_FILE_SIZE=$REACT_APP_MAX_FILE_SIZE" >> .env
  - echo "REACT_APP_TEST_API_BASE_URL=$REACT_APP_TEST_API_BASE_URL" > .env
  - echo "REACT_APP_TEST_FILE_URL=$REACT_APP_TEST_FILE_URL" >> .env

install:
  - yarn install

script:
  - yarn build

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - if [ -n "${TRAVIS_TAG}"  ]; then
    docker build -t poolchm/haribo:${TRAVIS_TAG} .;
    docker push poolchm/haribo:${TRAVIS_TAG};
    else
    docker build -t poolchm/haribo:latest .;
    docker push poolchm/haribo:latest;
    fi
