enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - ia32
    - x86
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.9.2.cjs
