nodeLinker: pnp

packageExtensions:
  "@types/redux-devtools-extension@^2.13.2":
    dependencies:
      redux: ^4.2.1
  antd-style@^3.6.1:
    dependencies:
      react-dom: ^18.2.0

supportedArchitectures:
  cpu:
    - ia32
    - x86
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.8.1.cjs
