nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.6.1.cjs

packageExtensions:
  "antd-style@^3.6.1":
    dependencies:
      "react": "^17.0.2"
      "react-dom": "^17.0.2"
  "@types/redux-devtools-extension@^2.13.2":
    dependencies:
      "redux": "^4.2.1"

# @see https://github.com/daangn/stackflow/blob/main/.yarnrc.yml
supportedArchitectures:
  cpu:
    - ia32
    - x86
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
