nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.6.1.cjs

# @see https://github.com/daangn/stackflow/blob/main/.yarnrc.yml
supportedArchitectures:
  cpu:
    - ia32
    - x86
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux