nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.6.1.cjs

packageExtensions:
  'antd-style@3.4.3':
    dependencies:
      'react': '17.0.2'
      'react-dom': '17.0.2'
  '@types/redux-devtools-extension@2.13.2':
    dependencies:
      'redux': '4.2.1'
