version: '1'
services:
  app:
    build:
      dockerfile: Dockerfile
    env_file: .env.production
    ports:
      - "3000:3000"
    stdin_open: true

  web:
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - web-logs:/var/log/nginx

volumes:
  web-logs:
