version: '1.1'
services:
  app:
    build: .
    env_file: .env.production
    volumes:
      - app-assets:/app/build
    stdin_open: true
    tty: true

  web:
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - web-logs:/var/log/nginx
      - app-assets:/var/www

volumes:
  web-logs:
  app-assets:
