version: '1'
services:
  web:
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - web-logs:/var/log/nginx

  app:
    container_name: "node"
    build:
      dockerfile: Dockerfile
    env_file: .env.production
    ports:
      - "3000:3000"


volumes:
  web-logs:
