version: '1'
services:
  app:
    build:
      dockerfile: Dockerfile
    env_file: .env.production
    environment:
      - VITE_API_BASE_URL=$VITE_API_BASE_URL
      - VITE_FILE_URL=$VITE_FILE_URL
      - VITE_MAX_FILE_SIZE=$VITE_MAX_FILE_SIZE
      - VITE_TEST_API_BASE_URL=$VITE_TEST_API_BASE_URL
      - VITE_TEST_FILE_URL=$VITE_TEST_FILE_URL
    stdin_open: true
    volumes:
      - app-assets:/app/build

  web:
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - web-logs:/var/log/nginx
      - app-assets:/var/www

volumes:
  web-logs:
  app-assets:
