version: '1'
services:
  app:
    build:
      dockerfile: Dockerfile
    env_file: .env.production
    volumes:
      - app-assets:/app/build
    stdin_open: true

  web:
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - web-logs:/var/log/nginx
      - app-assets:/var/www

volumes:
  web-logs:
  app-assets:
