const MENU = {
  INTRO: 'intro',
  MEMBERS: 'members',
  MEMBER: 'member',
  POST: 'post',
  PROJECTS: 'projects',
  PROJECT: 'project',
  ACTIVITIES: 'activities',
  ACTIVITY: 'activity',
  BOOKS: 'books',
  BOOK: 'book',
  APPLY: 'apply',
  ADMIN: 'admin',
  MYINFO: 'my-info',
  PASSWORD: 'password',
  RESET_PASSWORD: 'reset',
  SIGNIN: 'login',
  SIGNUP: 'register',
  FORBIDDEN: 'forbidden',
  NOT_FOUND: 'not-found',
  INTERVIEW_TIME: 'interview-time',
  BOARD: 'board',
  PKS: 'pks',
  POKEMON: 'pokemon',
  POKEMON_COLLECTION: 'collection',
  POKEMON_ACHIEVEMENTS: 'achievements',
  MY_PAGE: 'my-page',
  MY_PAGE_MY_POSTS: 'my-posts',
  MY_PAGE_MY_SCRAPS: 'my-scraps',
  MY_PAGE_COLLECTION: 'collection',
  MESSAGE: 'message',
  MESSAGE_FORM: 'form',
  ROOM_RESERVATION: 'room-reservation',
};

export { MENU };
