version: '1'
services:
  app:
    build:
      context: ../../.. # root
      dockerfile: ./apps/web-client/deploy/Dockerfile
    volumes:
      - app-assets:/app/apps/web-client/build

  web:
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - '80:80'
    volumes:
      - web-logs:/var/log/nginx
      - app-assets:/var/www
    restart: always

volumes:
  web-logs:
  app-assets:
