version: '1'
services:
  app:
    build:
      dockerfile: Dockerfile
    env_file: ../.env # @see https://stackoverflow.com/questions/48495663/docker-compose-env-file-not-working
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_FILE_URL=${VITE_FILE_URL}
      - VITE_MAX_FILE_SIZE=${VITE_MAX_FILE_SIZE}
    volumes:
      - app-assets:/app/build

  web:
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - web-logs:/var/log/nginx
      - app-assets:/var/www

volumes:
  web-logs:
  app-assets:
