name: deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: clone and execute
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PEM_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            DIRECTORY=dialga
            if [ -d "$DIRECTORY" ]
            then
              cd "$DIRECTORY/Dialga"
              git pull
            else
              mkdir $DIRECTORY
              cd $DIRECTORY
              git clone https://github.com/PoolC/Dialga.git
              cd Dialga
            fi
           
            _VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} 
            _VITE_FILE_URL=${{ secrets.VITE_FILE_URL }} 
            _VITE_MAX_FILE_SIZE=${{ secrets.VITE_MAX_FILE_SIZE }} 
            ENV_CONTENT="VITE_API_BASE_URL=$_VITE_API_BASE_URL
            VITE_FILE_URL=$_VITE_FILE_URL
            VITE_MAX_FILE_SIZE=$_VITE_MAX_FILE_SIZE"
            echo "$ENV_CONTENT" > .env.production
            
            docker compose down
            docker compose up -d --build
