name: web client deploy development

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: development
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: build
        run: |
          rm ./apps/web-client/.env && mv ./apps/web-client/.env.dev ./apps/web-client/.env
          yarn set version 3.8.1
          yarn install --immutable --immutable-cache
          yarn web-client codegen
          yarn web-client build

      - name: scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PEM_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ./apps/web-client/build/*
          target: ~/k8s/dialga/build
          strip_components: 3
