name: web client deploy development

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: development
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          # @see https://github.com/cypress-io/github-action#yarn-modern
          cache-dependency-path: ./yarn.lock

      - name: build
        run: |
          rm ./websites/poolc.org/.env && mv ./websites/poolc.org/.env.dev ./websites/poolc.org/.env
          yarn set version 4.9.2
          yarn install --immutable --immutable-cache
          yarn workspace @dialga/poolc.org build

      - name: scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PEM_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ./websites/poolc.org/build/*
          target: ~/k8s/dialga/build
          strip_components: 3
