name: web client deploy production

on:
  push:
    branches: [release/web-client]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: production # @TODO.. rename to 'web-client-deploy-production'
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          docker compose -f=./apps/web-client/deploy-app/docker-compose.yml up -d --build

      - name: scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PEM_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: './apps/web-client/build/*'
          target: /home/ubuntu/dialga/apps/web-client
